---
- name: Setup Docker, Docker Swarm, and Portainer
  hosts: ubuntu
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Install required packages for Docker installation
      ansible.builtin.apt:
        name:
          - docker-compose
          - python3-pip
          - libffi-dev
          - libssl-dev
          - curl
          - git
        state: present
    
    - name: Add 'pi' user to the docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      
    - name: Initialize Docker Swarm
      community.docker.docker_swarm:
        state: present
        
    - name: Deploy Portainer stack
      community.docker.docker_stack:
        state: present
        name: portainer
        compose:
          - version: "3.7"
            services:
              portainer:
                image: portainer/portainer-ce
                container_name: portainer
                command: -H unix:///var/run/docker.sock
                ports:
                  - "9000:9000"
                  - "8000:8000"
                volumes:
                  - /var/run/docker.sock:/var/run/docker.sock
                  - portainer_data:/data
            volumes:
              portainer_data: